### PR TITLE
Update rspec and its dependencies to ~> 3.0

### PR DESCRIPTION
**Pull request by Juanmcuello**
There are still many warnings, but at least the tests pass.

### CODE REVIEW

**Comment by igrigorik** [comment]
Awesome -- thank you!

**Comment by igrigorik** [comment]
Hmm, running specs locally.. I'm seeing 47 failures: https://gist.github.com/igrigorik/dc861503d93d2ea81fe8b89b5764ba24

Yet they're green on your end?

**Comment by Juanmcuello** [comment]
Yep, all green here. I updated the gist with my local result. As I can see, all tests pass even in travis-ci.

I'm running Ruby 2.3, but I tried with ruby 2.4 and tests run ok as well.

**Comment by igrigorik** [comment]
Err, interesting.. you're right, travis is green. Bizzaro, can't figure out why my local rspec runs are failing.

**Pull request merged**
