### PR TITLE
Add test_helper_sse to make it easier to test event streams.

### PR DESCRIPTION
**Pull request by aenain**
Hey,

As described in [https://github.com/postrank-labs/goliath/issues/308](https://github.com/postrank-labs/goliath/issues/308) testing event streams is tricky when using `goliath/test_helper`, because it requires `em-synchrony/em-http` which makes `EM::HttpRequest#get` synchronous.

To workaround this I have added `goliath/test_helper_sse`.

### CODE REVIEW

**Comment by igrigorik** [comment]
Apologies about the delay. This looks reasonable. 

@nolman @dj2 any objections?

**Comment by dj2** [comment]
Seems fine to me.

**Comment by igrigorik** [comment]
@aenain thanks for your patience :)

**Comment by aenain** [comment]
@igrigorik no problem :+1: thanks for merge :)

**Pull request merged**
