### PR TITLE
Add zero-downtime restarts

### PR DESCRIPTION
**Pull request by fatum**
## Example

See [fatum/goliath-zero-downtime](https://github.com/fatum/goliath-zero-downtime) project

## WTF Einhorn?

Einhorn came about when Stripe was investigating seamless code upgrading solutions for our API worker processes. We really liked the process model of Unicorn, but didn't want to use its HTTP functionality. So Einhorn was born, providing the master process functionality of Unicorn (and similar preforking servers) to a wider array of applications.

See https://stripe.com/blog/meet-einhorn for more background.

### CODE REVIEW

**Comment by igrigorik** [comment]
Code wise, looks sensible to me, and seems like a great feature... lgtm!

I'll wait for @dj2 or @nolman to second it.

**Comment by nolman** [comment]
LGTM

**Comment by igrigorik** [comment]
Done deal. @fatum: any chance we could also convince you to add a wiki page to explain the magic? :)

**Comment by fatum** [comment]
@igrigorik Done! https://github.com/postrank-labs/goliath/wiki/Zero-downtime-restart

i speak english badly and i think the page should be reviewed :)

**Comment by igrigorik** [comment]
Looks great, thanks once again!

**Comment by fatum** [comment]
@est thanks :)

**Pull request merged**
